productacquisition:
    path:     /
    defaults: { _controller: "AppBundle:ProductAcquisition:index" }

productacquisition_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ProductAcquisition:show" }

productacquisition_new:
    path:     /new
    defaults: { _controller: "AppBundle:ProductAcquisition:new" }

productacquisition_create:
    path:     /create
    defaults: { _controller: "AppBundle:ProductAcquisition:create" }
    methods:  POST

productacquisition_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ProductAcquisition:edit" }

productacquisition_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:ProductAcquisition:update" }
    methods:  [POST, PUT]

productacquisition_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ProductAcquisition:delete" }
    methods:  [POST, DELETE]
